SistemaCompeticao/SistemaCompeticao/Models/Artist_has_Music.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCompeticao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist_has_Music
    {
        public int Artist_idArtist { get; set; }
        public int Music_idMusic { get; set; }
        public int idArtist_has_Music { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Music Music { get; set; }
    }
}

SistemaCompeticao/SistemaCompeticao/Controllers/Artist_has_MusicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaCompeticao.Models;

namespace SistemaCompeticao.Controllers
{
    public class Artist_has_MusicController : Controller
    {
        private CompeticaoDB db = new CompeticaoDB();

        // GET: Artist_has_Music
        public ActionResult Index()
        {
            var artist_has_Music = db.Artist_has_Music.Include(a => a.Artist).Include(a => a.Music);
            return View(artist_has_Music.ToList());
        }

        // GET: Artist_has_Music/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist_has_Music artist_has_Music = db.Artist_has_Music.Find(id);
            if (artist_has_Music == null)
            {
                return HttpNotFound();
            }
            return View(artist_has_Music);
        }

        // GET: Artist_has_Music/Create
        public ActionResult Create()
        {
            ViewBag.Artist_idArtist = new SelectList(db.Artist, "idArtist", "Name");
            ViewBag.Music_idMusic = new SelectList(db.Music, "idMusic", "Title");
            return View();
        }

        // POST: Artist_has_Music/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Artist_idArtist,Music_idMusic,idArtist_has_Music")] Artist_has_Music artist_has_Music)
        {
            if (ModelState.IsValid)
            {
                db.Artist_has_Music.Add(artist_has_Music);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Artist_idArtist = new SelectList(db.Artist, "idArtist", "Name", artist_has_Music.Artist_idArtist);
            ViewBag.Music_idMusic = new SelectList(db.Music, "idMusic", "Title", artist_has_Music.Music_idMusic);
            return View(artist_has_Music);
        }

        // GET: Artist_has_Music/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist_has_Music artist_has_Music = db.Artist_has_Music.Find(id);
            if (artist_has_Music == null)
            {
                return HttpNotFound();
            }
            ViewBag.Artist_idArtist = new SelectList(db.Artist, "idArtist", "Name", artist_has_Music.Artist_idArtist);
            ViewBag.Music_idMusic = new SelectList(db.Music, "idMusic", "Title", artist_has_Music.Music_idMusic);
            return View(artist_has_Music);
        }

        // POST: Artist_has_Music/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Artist_idArtist,Music_idMusic,idArtist_has_Music")] Artist_has_Music artist_has_Music)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artist_has_Music).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Artist_idArtist = new SelectList(db.Artist, "idArtist", "Name", artist_has_Music.Artist_idArtist);
            ViewBag.Music_idMusic = new SelectList(db.Music, "idMusic", "Title", artist_has_Music.Music_idMusic);
            return View(artist_has_Music);
        }

        // GET: Artist_has_Music/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist_has_Music artist_has_Music = db.Artist_has_Music.Find(id);
            if (artist_has_Music == null)
            {
                return HttpNotFound();
            }
            return View(artist_has_Music);
        }

        // POST: Artist_has_Music/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Artist_has_Music artist_has_Music = db.Artist_has_Music.Find(id);
            db.Artist_has_Music.Remove(artist_has_Music);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaCompeticao/SistemaCompeticao/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaCompeticao.Models;

namespace SistemaCompeticao.Controllers
{
    public class ArtistsController : Controller
    {
        private CompeticaoDB db = new CompeticaoDB();

        // GET: Artists
        public ActionResult Index()
        {
            return View(db.Artist.ToList());
        }

        // GET: Artists/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artist.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // GET: Artists/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Artists/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idArtist,Name,FormationYear")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                db.Artist.Add(artist);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(artist);
        }

        // GET: Artists/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artist.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // POST: Artists/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idArtist,Name,FormationYear")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artist).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(artist);
        }

        // GET: Artists/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artist.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // POST: Artists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Artist artist = db.Artist.Find(id);
            db.Artist.Remove(artist);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaCompeticao/SistemaCompeticao/Controllers/MusicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaCompeticao.Models;

namespace SistemaCompeticao.Controllers
{
    public class MusicsController : Controller
    {
        private CompeticaoDB db = new CompeticaoDB();

        // GET: Musics
        public ActionResult Index()
        {
            return View(db.Music.ToList());
        }

        // GET: Musics/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = db.Music.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // GET: Musics/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Musics/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idMusic,Title,MusicLength,Genre")] Music music)
        {
            if (ModelState.IsValid)
            {
                db.Music.Add(music);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(music);
        }

        // GET: Musics/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = db.Music.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // POST: Musics/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idMusic,Title,MusicLength,Genre")] Music music)
        {
            if (ModelState.IsValid)
            {
                db.Entry(music).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(music);
        }

        // GET: Musics/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = db.Music.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // POST: Musics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Music music = db.Music.Find(id);
            db.Music.Remove(music);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaCompeticao/SistemaCompeticao/Views/Artist_has_Music/Create.cshtml
@model SistemaCompeticao.Models.Artist_has_Music

@{
    ViewBag.Title = "Cadastrar Participação";
}

<h2>Cadastrar Participação</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Participação</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Artist_idArtist, "Nome do Artista", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Artist_idArtist", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Artist_idArtist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Music_idMusic, "Título da Música", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Music_idMusic", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Music_idMusic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaCompeticao/SistemaCompeticao/Views/Artist_has_Music/Delete.cshtml
@model SistemaCompeticao.Models.Artist_has_Music

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir Participação</h2>

<h3>Tem certeza que deseja excluir?</h3>

<div>
    <h4>Participação</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Music.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Music.Title)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar para Lista", "Index")
        </div>
    }
</div>

SistemaCompeticao/SistemaCompeticao/Views/Artist_has_Music/Details.cshtml
@model SistemaCompeticao.Models.Artist_has_Music

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>Participação</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </dt>

        <dd>
            @Html.ActionLink(@Model.Artist.Name, "Details", "Artists", new { @id = Model.Artist.idArtist }, null)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Music.Title)
        </dt>

        <dd>
            @Html.ActionLink(@Model.Music.Title, "Details", "Musics", new { @id = Model.Music.idMusic }, null)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.idArtist_has_Music }) |
    @Html.ActionLink("Voltar para Lista", "Index")
</p>

SistemaCompeticao/SistemaCompeticao/Views/Artist_has_Music/Edit.cshtml
@model SistemaCompeticao.Models.Artist_has_Music

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Participação</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idArtist_has_Music)

        <div class="form-group">
            @Html.LabelFor(model => model.Artist_idArtist, "Nome do Artista", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Artist_idArtist", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Artist_idArtist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Music_idMusic, "Título da Música", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Music_idMusic", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Music_idMusic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listar participações", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SistemaCompeticao/SistemaCompeticao/Views/Artist_has_Music/Index.cshtml
@model IEnumerable<SistemaCompeticao.Models.Artist_has_Music>

@{
    ViewBag.Title = "Participações em Músicas";
}

<h2>Lista de Participações</h2>

<p>
    @Html.ActionLink("Cadastrar Participação", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Music.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Artist.Name, "Details", "Artists", new { @id = item.Artist.idArtist }, null)
        </td>
        <td>
            @Html.ActionLink(item.Music.Title, "Details", "Musics", new { @id = item.Music.idMusic }, null)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.idArtist_has_Music }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.idArtist_has_Music }) |
            @Html.ActionLink("Deletar", "Delete", new { id=item.idArtist_has_Music })
        </td>
    </tr>
}

</table>